name: Build WASM Examples
on:
  workflow_dispatch:
jobs:
  build:
    name: Build WASM 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout raylib.com
        uses: actions/checkout@v3
      - name: Checkout raylib
        uses: actions/checkout@v3
        with:
          path: raylibsrc
          repository: raysan5/raylib
      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: Build raylib WASM
        run: |
          cd raylibsrc/src
          make PLATFORM=PLATFORM_WEB -B
      - name: Build Core Examples
        run: |
          cd raylibsrc/examples
          make PLATFORM=PLATFORM_WEB core
      - name: Update example tags
        run: ./tools/update-example-tags.sh ./raylibsrc/examples
      - name: Copy files over
        run: cp -r ./raylibsrc/examples/* ./examples/
      - name: Commit changes
        run: cat ./examples/core/core_2d_camera_mouse_zoom.html